data_path:
  # テスト用フォルダ
  rawData_path: "../00_Data/00_RawData"
  rawData_period_folder_name: "202104-202403A"

  # データベース用フォルダ
  rawData_output_DB_folder_name: "../00_Data/00_RawData_DB"
  preprocessed_folder_path: "../00_Data/01_PreProcessData"

  output_folder_path: "../00_Data/03_Output/"
  predict_data_path: "../00_Data/01_PreProcessData/preprocessed_data.csv"

  term_file_path: "../期間設定.xlsx"
  master_data_path: "../マスタデータ.xlsx"

  # ローカルに以降するファイルのパス
  filename_for_preprocess_path: "data_module/data/CommonData/filename.xlsx"
  dict_column_name_path: "data_module/data/CommonData/preprocessed_column_name.xlsx"
  dict_column_name_experiment_path: "data_module/data/CommonData/説明変数.xlsx"
  df_for_normalize_path: "data_module/data/NormalizedData"

  train_memory_path: "data_module/data/CommonData/学習履歴.csv"
  pkl_path: "data_module/data/ModelBackUp/"
